const COLORS={accent:'--accent',accent2:'--accent-2',danger:'--danger',warning:'--warning',good:'--good'};
const players=[
{id:'roy',name:'Émilie Roy',no:28,pos:'AG',age:19,city:'QUÉBEC',type:'Marqueur',gp:24,g:3,a:4,pts:7,attrs:{MAN:4,TIR:6,PUI:3,PAT:7,IQ:3,'CRÉ':5,'CŒ':7},salary:.85,years:2,height:'5 pi 7',weight:'142 lb',league:1,team:1,potential:'Élevé',personality:'Audacieuse',culture:'Rebelle',social:'Conciliant',traits:['Rapide','Instinctive'],health:'En santé'},
{id:'gagnon',name:'Alexis Gagnon',no:14,pos:'C',age:27,city:'QUÉBEC',type:'Polyvalent',gp:24,g:6,a:10,pts:16,attrs:{MAN:6,TIR:5,PUI:6,PAT:5,IQ:7,'CRÉ':4,'CŒ':7},salary:3.2,years:1,height:'6 pi 1',weight:'201 lb',league:6,team:4,potential:'Faible',personality:'Loyal',culture:'Rebelle',social:'Conciliant',traits:['Fiable','Collectif'],health:'En santé'},
{id:'sokolov',name:'Viktor Sokolov',no:91,pos:'AD',age:31,city:'QUÉBEC',type:'Marqueur',gp:24,g:17,a:15,pts:32,attrs:{MAN:10,TIR:12,PUI:8,PAT:7,IQ:10,'CRÉ':11,'CŒ':6},salary:10.5,years:3,height:'6 pi 0',weight:'194 lb',league:11,team:2,potential:'Très faible',personality:'Ambitieux',culture:'Anarchiste',social:'Exigeant',traits:['Sniper','Vedette'],health:'En santé'},
{id:'fortin',name:'Sarah Fortin',no:7,pos:'AG',age:22,city:'QUÉBEC',type:'Fabricant de jeux',gp:24,g:4,a:14,pts:18,attrs:{MAN:7,TIR:4,PUI:3,PAT:8,IQ:6,'CRÉ':8,'CŒ':5},salary:1.4,years:2,height:'5 pi 8',weight:'149 lb',league:3,team:2,potential:'Bon',personality:'Créative',culture:'Libre',social:'Conciliant',traits:['Passeuse','Créative'],health:'En santé'},
{id:'leclerc',name:'Hugo Leclerc',no:44,pos:'C',age:25,city:'QUÉBEC',type:'Attaquant de puissance',gp:24,g:8,a:6,pts:14,attrs:{MAN:4,TIR:6,PUI:9,PAT:4,IQ:5,'CRÉ':3,'CŒ':8},salary:2.8,years:3,height:'6 pi 3',weight:'224 lb',league:5,team:3,potential:'Moyen',personality:'Intense',culture:'Conformiste',social:'Direct',traits:['Physique','Protecteur'],health:'En santé'},
{id:'morin',name:'Jules Morin',no:16,pos:'AD',age:24,city:'QUÉBEC',type:'Polyvalent',gp:24,g:5,a:8,pts:13,attrs:{MAN:5,TIR:5,PUI:5,PAT:6,IQ:6,'CRÉ':5,'CŒ':7},salary:2.1,years:2,height:'5 pi 11',weight:'184 lb',league:4,team:4,potential:'Moyen',personality:'Stable',culture:'Conformiste',social:'Facile',traits:['Adaptable','Constant'],health:'En santé'}
];
const defaultOrder={line:['roy','gagnon','sokolov'],bench:['fortin','leclerc','morin']};
let order=JSON.parse(localStorage.getItem('hockey-order')||'null')||structuredClone(defaultOrder);
let favorites=new Set(JSON.parse(localStorage.getItem('hockey-favorites')||'[]'));
let selected='gagnon';
const $=s=>document.querySelector(s);
function maxAttr(p){return Math.max(...Object.values(p.attrs))}
function fmtMoney(v){return (String(v).replace('.',','))+' M$'}
function card(p){const attrs=Object.entries(p.attrs).map(([k,v])=>`<div class="attr" style="--v:${v}"><small>${k}</small><b>${v}</b></div>`).join('');return `<article class="player-card" draggable="true" data-id="${p.id}"><div class="card-head"><div><div class="player-name">${p.name}</div><div class="player-meta">${p.pos} · ${p.age} ans · ${p.city} · ${p.type}</div></div><button class="favorite ${favorites.has(p.id)?'on':''}" data-fav="${p.id}" aria-label="Favori">★</button></div><div class="stat-strip"><div class="mini-stat"><small>MJ</small><b>${p.gp}</b></div><div class="mini-stat"><small>B</small><b>${p.g}</b></div><div class="mini-stat"><small>A</small><b>${p.a}</b></div><div class="mini-stat"><small>PTS</small><b>${p.pts}</b></div></div><div class="attributes">${attrs}</div><div class="contract"><span>${fmtMoney(p.salary)} / an · ${p.years} an${p.years>1?'s':''}</span><span class="status-good">✓ ${p.health}</span></div><div class="card-actions"><button data-detail="${p.id}">Fiche</button><button data-flip="${p.id}">Profil</button></div></article>`}
function renderCards(){for(const zone of ['line','bench']){const el=zone==='line'?$('#firstLine'):$('#bench');el.innerHTML=order[zone].map(id=>card(players.find(p=>p.id===id))).join('')}}
function renderDetail(id){const p=players.find(x=>x.id===id)||players[0];selected=p.id;const avg=(Object.values(p.attrs).reduce((a,b)=>a+b,0)/7).toFixed(1).replace('.',',');$('#detailPanel').innerHTML=`<div class="detail-header"><div><span class="eyebrow">${p.city} · PROFIL ACTUEL</span><h3>#${p.no} ${p.name}</h3><div class="muted">${p.age} ans · ${p.pos} · ${p.height} · ${p.weight} · ${p.type}</div></div><button class="favorite ${favorites.has(p.id)?'on':''}" data-fav="${p.id}">★</button></div><div class="detail-grid"><div class="metric-box"><small>Attribut moyen</small><b>${avg} / 15</b><div class="bar"><span style="--w:${Math.min(100,maxAttr(p)/15*100)}%"></span></div></div><div class="metric-box"><small>Potentiel de développement</small><b>${p.potential}</b></div><div class="metric-box"><small>Expérience</small><b>${p.league}e saison en ligue · ${p.team}e avec Québec</b></div><div class="metric-box"><small>Contrat</small><b>${fmtMoney(p.salary)} / an · ${p.years} saison${p.years>1?'s':''} restante${p.years>1?'s':''}</b></div><div class="metric-box"><small>Culture</small><b>${p.culture}</b><div class="trait-list"><span class="trait">Conformiste ↔ Anarchiste</span></div></div><div class="metric-box"><small>Facilité à jouer avec</small><b>${p.social}</b><div class="trait-list">${p.traits.map(t=>`<span class="trait">${t}</span>`).join('')}</div></div></div>`;bindActions()}
function filtered(){const pos=$('#positionFilter').value,type=$('#typeFilter').value,age=+$('#ageFilter').value,min=+$('#ratingFilter').value,q=$('#globalSearch').value.trim().toLowerCase();return players.filter(p=>(!pos||p.pos===pos)&&(!type||p.type===type)&&p.age<=age&&maxAttr(p)>=min&&(!q||`${p.name} ${p.type} ${p.pos}`.toLowerCase().includes(q)))}
function renderTable(){const data=filtered();$('#resultCount').textContent=data.length;$('#playersTable').innerHTML=data.map(p=>`<tr data-row="${p.id}"><td><b>${p.name}</b><div class="muted">#${p.no} · ${p.age} ans</div></td><td>${p.pos}</td>${Object.values(p.attrs).map(v=>`<td>${v}</td>`).join('')}<td>${fmtMoney(p.salary)} · ${p.years}a</td><td class="status-good">${p.health}</td></tr>`).join('')||'<tr><td colspan="11" class="empty">Aucun joueur.</td></tr>';document.querySelectorAll('[data-row]').forEach(r=>r.onclick=()=>renderDetail(r.dataset.row))}
function salary(){const total=players.reduce((s,p)=>s+p.salary,0);$('#salaryTotal').textContent=`${fmtMoney(+total.toFixed(2))} / 25 M$`;$('#salaryAvailable').textContent=fmtMoney(+(25-total).toFixed(2));$('#salaryFill').style.width=`${Math.min(100,total/25*100)}%`}
function bindActions(){document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();favorites.has(b.dataset.fav)?favorites.delete(b.dataset.fav):favorites.add(b.dataset.fav);localStorage.setItem('hockey-favorites',JSON.stringify([...favorites]));$('#favoriteCount').textContent=favorites.size;renderCards();renderDetail(selected)});document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>renderDetail(b.dataset.detail));document.querySelectorAll('[data-flip]').forEach(b=>b.onclick=()=>renderDetail(b.dataset.flip));document.querySelectorAll('.player-card').forEach(c=>{c.ondragstart=()=>{c.classList.add('dragging');window.dragId=c.dataset.id};c.ondragend=()=>c.classList.remove('dragging')});document.querySelectorAll('[data-zone]').forEach(z=>{z.ondragover=e=>e.preventDefault();z.ondrop=e=>{e.preventDefault();const id=window.dragId;if(!id)return;for(const k of ['line','bench'])order[k]=order[k].filter(x=>x!==id);const target=z.dataset.zone;order[target].push(id);if(order.line.length>3){order.bench.unshift(order.line.shift())}if(order.bench.length>3){order.line.push(order.bench.shift())}localStorage.setItem('hockey-order',JSON.stringify(order));renderCards();bindActions()}})}
function renderAll(){renderCards();renderDetail(selected);renderTable();salary();$('#favoriteCount').textContent=favorites.size;bindActions()}
['positionFilter','typeFilter','ageFilter','ratingFilter','globalSearch'].forEach(id=>$('#'+id).addEventListener('input',()=>{$('#ageValue').textContent=$('#ageFilter').value;$('#ratingValue').textContent=$('#ratingFilter').value;renderTable()}));
$('#clearFilters').onclick=()=>{$('#positionFilter').value='';$('#typeFilter').value='';$('#ageFilter').value=35;$('#ratingFilter').value=1;$('#globalSearch').value='';$('#ageValue').textContent='35';$('#ratingValue').textContent='1';renderTable()};
$('#themeToggle').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('hockey-theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('hockey-theme')==='light')document.body.classList.add('light');
$('#resetBtn').onclick=()=>{localStorage.removeItem('hockey-order');localStorage.removeItem('hockey-favorites');order=structuredClone(defaultOrder);favorites=new Set();renderAll()};
$('#menuToggle').onclick=()=>$('#sidebar').classList.toggle('open');
const cv=$('#particles'),ctx=cv.getContext('2d');let pts=[],mouse={x:-1e3,y:-1e3};function resize(){cv.width=innerWidth*devicePixelRatio;cv.height=innerHeight*devicePixelRatio;cv.style.width=innerWidth+'px';cv.style.height=innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();addEventListener('pointermove',e=>{mouse={x:e.clientX,y:e.clientY};if(Math.random()>.55)pts.push({x:mouse.x,y:mouse.y,vx:(Math.random()-.5)*.45,vy:(Math.random()-.5)*.45-0.18,a:.24,r:Math.random()*1.2+.3})});function tick(){ctx.clearRect(0,0,innerWidth,innerHeight);const c=getComputedStyle(document.body).getPropertyValue('--accent').trim()||'#b7ff3c';pts=pts.filter(p=>p.a>.01);for(const p of pts){p.x+=p.vx;p.y+=p.vy;p.a*=.975;ctx.globalAlpha=p.a;ctx.fillStyle=c;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;requestAnimationFrame(tick)}tick();
renderAll();
