import {roster,recordFor,clubOf,teams} from './app/league';
import {labels,playStyleMeaning} from './app/players';
import {metrics} from './app/advanced-stats';
import {meanings,definitions} from './stats-definitions';
import './stats-panel.css';
const f=(n:number)=>n.toLocaleString('fr-CA',{maximumFractionDigits:2});
document.querySelector('#panel')!.innerHTML=`<header><h1>Statistiques</h1><a href="stats.html" target="_blank" rel="noopener">Vue complète ↗</a></header><label for="referencePlayer">Joueur de référence</label><select id="referencePlayer">${roster.map(p=>`<option value="${p.id}">${p.name} · ${teams.find(t=>t.id===clubOf(p.id))!.name}</option>`).join('')}</select><p class="note">Valeurs de référence / 15. Les résultats des expériences restent affichés dans leur module.</p><div id="referenceData"></div>`;
const select=document.querySelector<HTMLSelectElement>('#referencePlayer')!;
function render(){const p=roster.find(p=>p.id===select.value)!;const m=metrics(p.id)!;document.querySelector('#referenceData')!.innerHTML=`<p class="identity">${p.pos} · ${p.age} ans · ${p.type} · style ${p.playStyle.toLowerCase()}</p><dl class="attributes">${labels.map((l,i)=>`<div><dt><abbr title="${meanings[i]}">${l}</abbr></dt><dd>${p.stats[i]}<small> / 15</small></dd></div>`).join('')}</dl><details><summary>Signification des attributs</summary>${labels.map((l,i)=>`<p><b>${l}</b> — ${meanings[i]}</p>`).join('')}</details><details><summary>Profil et contrat</summary><p>${playStyleMeaning}</p><p>${p.trait} · potentiel ${p.potential.toLowerCase()}</p><p>${f(p.salary)} M$ / an · ${p.years} saison(s) restante(s)</p><p>Personnalité : ${p.axes[0]}/100 de rebelle à conformiste; ${p.axes[1]}/100 d’intransigeant à conciliant.</p></details><section><h2>Historique · toutes situations</h2><p class="note">MJ : matchs · B : buts · A : passes · P : points</p><table><thead><tr><th>Période</th><th>MJ</th><th>B</th><th>A</th><th>P</th></tr></thead><tbody>${['2028-2029','2027-2028'].flatMap(s=>['regular','playoffs'].map(phase=>{const r=recordFor(p,s,phase);return `<tr><th>${s}<small>${phase==='regular'?'Régulière':'Séries'}</small></th>${r?[r.gp,r.goals,r.assists,r.goals+r.assists].map(v=>`<td>${v}</td>`).join(''):'<td colspan="4">Non disponible</td>'}</tr>`})).join('')}</tbody></table></section><details><summary>20 mesures avancées · 2028–2029</summary><p class="note">Saison régulière, à 5 contre 5. Observations fictives indépendantes des attributs.</p>${Object.entries(definitions).map(([key,[name,meaning]])=>`<p><b>${name} : ${f(m[key as keyof typeof m])}</b><br>${meaning}</p>`).join('')}</details>`;}
select.onchange=render;render();

import './app/ui-gym-foundation.css';
