import {roster,recordFor,clubOf,teams} from './app/league';
import {labels,playStyleMeaning} from './app/players';
import {metrics} from './app/advanced-stats';
import './stats.css';
import {meanings,definitions} from './stats-definitions';
const fmt=(n:number)=>n.toLocaleString('fr-CA',{maximumFractionDigits:2});
const table=(headers:string[],rows:(string|number)[][])=>`<div class="scroll"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
document.querySelector('#statsApp')!.innerHTML=`<nav><a href="./">UI Gym</a><a href="gameplay.html">Gameplay Gym</a></nav><header><p>HOCKEY · LABORATOIRE</p><h1>Gym des statistiques</h1><p>Les 18 joueurs du UI Gym, leurs attributs, leurs saisons et le sens de chaque mesure.</p></header><p class="notice">Toutes les données sont fictives. Cette page lit les données de référence du UI Gym; les modifications temporaires faites dans un autre écran ne sont pas synchronisées. Aucun attribut historique n’est inventé.</p><label>Joueur <select id="player">${roster.map(p=>`<option value="${p.id}">${p.name} · ${teams.find(t=>t.id===clubOf(p.id))!.name}</option>`).join('')}</select></label><section id="profile"></section><section><h2>Statistiques avancées · 5 contre 5</h2><label>Période <select id="period"><option value="2028-2029|regular">2028–2029 · saison régulière</option><option value="2027-2028|regular">2027–2028 · saison régulière</option><option value="2027-2028|playoffs">2027–2028 · séries</option></select></label><p>Observations fictives indépendantes des attributs. Les buts et passes à 5 contre 5 sont un sous-ensemble des totaux de saison. Un pourcentage de possession ne mesure pas le talent individuel.</p><div id="advanced"></div></section>`;
const player=document.querySelector<HTMLSelectElement>('#player')!,period=document.querySelector<HTMLSelectElement>('#period')!;
function advanced(){const [season,phase]=period.value.split('|'),m=metrics(player.value,season,phase);document.querySelector('#advanced')!.innerHTML=table(['Mesure','Valeur','Signification / calcul'],Object.entries(definitions).map(([key,[title,meaning]])=>[title,m?fmt(m[key as keyof typeof m]):'Non disponible',meaning]));}
function render(){const p=roster.find(p=>p.id===player.value)!;document.querySelector('#profile')!.innerHTML=`<h2>${p.name} · #${p.num}</h2>${table(['Donnée','Valeur','Signification'],[['Position',p.pos,'C : centre · AG : aile gauche · AD : aile droite'],['Âge',p.age,'Âge dans la saison actuelle'],['Gabarit',`${p.height} · ${p.weight} lb`,'Taille et poids'],['Rôle',p.type,'Rôle de jeu du prototype'],['Style de jeu',p.playStyle,playStyleMeaning],['Personnalité',p.trait,'Trait de caractère; aucun bonus automatique défini ici'],['Rebelle → conformiste',p.axes[0]+'/100','0 : rebelle; 100 : conformiste'],['Intransigeant → conciliant',p.axes[1]+'/100','0 : intransigeant; 100 : conciliant'],['Potentiel',p.potential,'Catégorie qualitative de progression, pas une hausse garantie'],['Salaire',`${fmt(p.salary)} M$`,'Salaire annuel'],['Contrat',`${p.years} an(s)`,'Durée restante'],['Ancienneté en ligue',p.league,'Nombre de saisons'],['Ancienneté au club',p.team,'Nombre de saisons']])}<h2>Les sept attributs · échelle de 1 à 15</h2><p>Valeurs actuelles de référence. Les effets exacts dépendent du module; ces définitions décrivent l’intention de design.</p>${table(['Attribut','Note / 15','Signification'],labels.map((l,i)=>[l,p.stats[i],meanings[i]]))}<h2>Historique de saison · toutes situations</h2><p>Toujours affiché, indépendamment du choix de période ci-dessous. MJ = matchs joués; points = buts + passes. « Non disponible » signifie absence de données, pas zéro.</p>${table(['Saison','Phase','MJ','Buts','Passes','Points'],['2028-2029','2027-2028'].flatMap(s=>['regular','playoffs'].map(phase=>{const r=recordFor(p,s,phase);return [s,phase==='regular'?'Régulière':'Séries',...(r?[r.gp,r.goals,r.assists,r.goals+r.assists]:Array(4).fill('Non disponible'))]})))}`;advanced()}
player.onchange=render;period.onchange=advanced;render();

import './app/ui-gym-foundation.css';
