"use client";
import {useState} from "react";
import {UserCircleIcon} from "@phosphor-icons/react/dist/csr/UserCircle";
import {UsersThreeIcon} from "@phosphor-icons/react/dist/csr/UsersThree";
import {StarIcon} from "@phosphor-icons/react/dist/csr/Star";
import {TrophyIcon} from "@phosphor-icons/react/dist/csr/Trophy";
import {TargetIcon} from "@phosphor-icons/react/dist/csr/Target";
import {LightningIcon} from "@phosphor-icons/react/dist/csr/Lightning";
import {BarbellIcon} from "@phosphor-icons/react/dist/csr/Barbell";
import {BrainIcon} from "@phosphor-icons/react/dist/csr/Brain";
import {LightbulbIcon} from "@phosphor-icons/react/dist/csr/Lightbulb";
import {HeartIcon} from "@phosphor-icons/react/dist/csr/Heart";
import {ShieldCheckIcon} from "@phosphor-icons/react/dist/csr/ShieldCheck";
import {FirstAidKitIcon} from "@phosphor-icons/react/dist/csr/FirstAidKit";
import {TrendUpIcon} from "@phosphor-icons/react/dist/csr/TrendUp";
import {HandshakeIcon} from "@phosphor-icons/react/dist/csr/Handshake";
import {CurrencyDollarIcon} from "@phosphor-icons/react/dist/csr/CurrencyDollar";
import {SignatureIcon} from "@phosphor-icons/react/dist/csr/Signature";
import {ArrowsLeftRightIcon} from "@phosphor-icons/react/dist/csr/ArrowsLeftRight";
import {BinocularsIcon} from "@phosphor-icons/react/dist/csr/Binoculars";
import {ChartLineUpIcon} from "@phosphor-icons/react/dist/csr/ChartLineUp";
import {ClockCounterClockwiseIcon} from "@phosphor-icons/react/dist/csr/ClockCounterClockwise";
import {BellIcon} from "@phosphor-icons/react/dist/csr/Bell";
import {SlidersHorizontalIcon} from "@phosphor-icons/react/dist/csr/SlidersHorizontal";
import {MagnifyingGlassIcon} from "@phosphor-icons/react/dist/csr/MagnifyingGlass";
import {ArrowClockwiseIcon} from "@phosphor-icons/react/dist/csr/ArrowClockwise";
export const gameIcons={UserCircle:UserCircleIcon,UsersThree:UsersThreeIcon,Star:StarIcon,Trophy:TrophyIcon,Target:TargetIcon,Lightning:LightningIcon,Barbell:BarbellIcon,Brain:BrainIcon,Lightbulb:LightbulbIcon,Heart:HeartIcon,ShieldCheck:ShieldCheckIcon,FirstAidKit:FirstAidKitIcon,TrendUp:TrendUpIcon,Handshake:HandshakeIcon,CurrencyDollar:CurrencyDollarIcon,Signature:SignatureIcon,ArrowsLeftRight:ArrowsLeftRightIcon,Binoculars:BinocularsIcon,ChartLineUp:ChartLineUpIcon,ClockCounterClockwise:ClockCounterClockwiseIcon,Bell:BellIcon,SlidersHorizontal:SlidersHorizontalIcon,MagnifyingGlass:MagnifyingGlassIcon,ArrowClockwise:ArrowClockwiseIcon};
const icons=[{Icon:UserCircleIcon,label:"Joueur"},{Icon:UsersThreeIcon,label:"Équipe"},{Icon:StarIcon,label:"Favori"},{Icon:TrophyIcon,label:"Trophée"},{Icon:TargetIcon,label:"Tir"},{Icon:LightningIcon,label:"Patinage"},{Icon:BarbellIcon,label:"Puissance"},{Icon:BrainIcon,label:"IQ hockey"},{Icon:LightbulbIcon,label:"Créativité"},{Icon:HeartIcon,label:"Cœur"},{Icon:ShieldCheckIcon,label:"Santé"},{Icon:FirstAidKitIcon,label:"Blessure"},{Icon:TrendUpIcon,label:"Développement"},{Icon:HandshakeIcon,label:"Chimie"},{Icon:CurrencyDollarIcon,label:"Salaire"},{Icon:SignatureIcon,label:"Contrat"},{Icon:ArrowsLeftRightIcon,label:"Échange"},{Icon:BinocularsIcon,label:"Recrutement"},{Icon:ChartLineUpIcon,label:"Statistiques"},{Icon:ClockCounterClockwiseIcon,label:"Historique"},{Icon:BellIcon,label:"Notification"},{Icon:SlidersHorizontalIcon,label:"Filtres"},{Icon:MagnifyingGlassIcon,label:"Recherche"},{Icon:ArrowClockwiseIcon,label:"Retourner"}];
export function IconKit(){const [weight,setWeight]=useState<'regular'|'bold'|'fill'|'duotone'>('duotone');return <><p>Phosphor · Un kit existant, avec des symboles réutilisables pour les joueurs, la gestion et la navigation.</p><div className="il-segments" aria-label="Style des icônes">{(['regular','bold','fill','duotone'] as const).map((w,i)=><button key={w} aria-pressed={weight===w} onClick={()=>setWeight(w)}>{['Fin','Gras','Plein','Duo'][i]}</button>)}</div><div className="gym-icons">{icons.map(({Icon,label})=><div key={label}><Icon size={34} weight={weight} aria-hidden="true"/><span>{label}</span></div>)}</div><p className="il-muted">Proposition : Duo pour les systèmes du jeu, Gras pour les actions. Les libellés restent visibles pour éviter les symboles ambigus.</p><a href="https://phosphoricons.com/" target="_blank" rel="noreferrer">Explorer le kit Phosphor ↗</a></>}
