"use client";
import {useEffect,useRef,useState} from 'react';
import {labels} from './players';
import {meanings,definitions} from '../stats-definitions';
import {rawLabels} from './hockey-player-model';
import {freshPlayer,validPlayer,migratePlayer,playerSummary,observations,axes,type WorkbenchPlayer} from './player-workbench-model';
import {statColor} from './stat-color';
import {Radar} from './player-radar';
import {PlayerDesignGuide} from './player-design-guide';
import './hockey-player-gym.css';
const fmt=(n:number|null)=>n===null?'Non calculable':n.toLocaleString('fr-CA',{maximumFractionDigits:2});
const STORAGE='hockey-player-workbench-v2';
function NumberField({label,value,onChange,min=0,max=100,step=1}:{label:string;value:number;onChange:(v:number)=>void;min?:number;max?:number;step?:number}){return <label>{label}<input type="number" aria-label={label} value={value} min={min} max={max} step={step} onChange={e=>{if(e.target.value!==''&&Number.isFinite(Number(e.target.value)))onChange(Math.max(min,Math.min(max,Number(e.target.value))))}}/></label>}
function Source({children}:{children:React.ReactNode}){return <p className="wb-source">{children}</p>}
export function HockeyPlayerGym(){const [p,setP]=useState(freshPlayer),[ready,setReady]=useState(false),[status,setStatus]=useState(''),[note,setNote]=useState('');const latest=useRef(p);
useEffect(()=>{try{const current=JSON.parse(localStorage.getItem(STORAGE)||'null');if(validPlayer(current))setP(current);else{const migrated=migratePlayer(JSON.parse(localStorage.getItem('hockey-player-template-v1')||'null'));if(migrated){setP(migrated);setStatus('Ancien brouillon repris : attributs de base conservés, anciens bonus retirés. Axes convertis en trois positions; Créatif devient Neutre. L’ancien brouillon reste sauvegardé séparément.')}}}catch{setStatus('Brouillon illisible : modèle neutre chargé.')}setReady(true)},[]);
useEffect(()=>{latest.current=p;if(!ready)return;const timer=setTimeout(()=>{try{localStorage.setItem(STORAGE,JSON.stringify(p))}catch{setStatus('Sauvegarde indisponible : exporte ton joueur.')}},300);return()=>clearTimeout(timer)},[p,ready]);
useEffect(()=>{const save=()=>{try{localStorage.setItem(STORAGE,JSON.stringify(latest.current))}catch{}};window.addEventListener('pagehide',save);return()=>window.removeEventListener('pagehide',save)},[]);
function update(fn:(d:WorkbenchPlayer)=>void){setP(old=>{const d=structuredClone(old);fn(d);return d})}
const c=playerSummary(p),metrics=observations(p);
function exportPlayer(){const url=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='hockey-player-v2.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
return <section className="hp-gym wb-gym"><header><span className="eyebrow">HOCKEY PLAYER · ATELIER DE CONCEPTION</span><h2>Un joueur, un seul modèle.</h2><p>Tu modifies un joueur de test. Dans le jeu, le DG choisit son utilisation, ses partenaires et ses contrats; il ne règle pas ses attributs ou sa personnalité.</p><div className="hp-actions"><button className="quiet-btn" onClick={exportPlayer}>Exporter le joueur</button><label className="quiet-btn">Importer<input type="file" accept=".json,application/json" aria-label="Importer le joueur" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>300000)throw Error();const data=JSON.parse(await file.text()),next=validPlayer(data)?data:migratePlayer(data);if(!next)throw Error();setP(next);setStatus('Joueur importé. Les anciens bonus ne sont pas utilisés.')}catch{setStatus('Import refusé : données invalides.')}e.target.value=''}}/></label></div><p role="status">{status||'Modifications sauvegardées automatiquement sur cet appareil.'}</p></header>
<details className="wb-reference"><summary>Modèle du joueur · décisions et développement annuel</summary><PlayerDesignGuide/></details>
<nav className="wb-nav" aria-label="Sections du joueur">{[['identity','Identité'],['attributes','Attributs'],['development','Développement'],['temperament','Personnalité et style'],['context','Contexte'],['career','Carrière'],['contract','Contrat']].map(([id,title])=><a key={id} href={'#wb-'+id}>{title}</a>)}</nav>
<div className="wb-layout"><div>
<section id="wb-identity"><h3>Identité et parcours</h3><Source>Origine : identité et gabarit à la création; âge et saisons liés au parcours. Ici, saisie de test sans effet automatique sur les attributs. La croissance depuis l’âge 0 reste à concevoir.</Source><div className="hp-fields"><label>Nom<input value={p.identity.name} maxLength={200} onChange={e=>update(d=>{d.identity.name=e.target.value})}/></label><label>Position<select value={p.identity.pos} onChange={e=>update(d=>{d.identity.pos=e.target.value})}>{['AG','C','AD'].map(v=><option key={v}>{v}</option>)}</select></label>{(['num','age','weight','league','team'] as const).map((k,i)=><NumberField key={k} label={['Numéro','Âge','Poids (lb)','Saisons en ligue','Saisons au club'][i]} value={p.identity[k]} max={k==='weight'?400:k==='num'?99:100} onChange={v=>update(d=>{d.identity[k]=v})}/>)}<label>Taille<input value={p.identity.height} maxLength={200} onChange={e=>update(d=>{d.identity.height=e.target.value})}/></label></div></section>
<section id="wb-attributes"><h3>Les sept attributs · capacités actuelles</h3><Source>Origine : base du joueur, appelée à évoluer au fil des saisons. Ici, la valeur saisie est la valeur affichée : aucun bonus de profil, de style ou de personnalité. Les profils sont mis de côté.</Source>{labels.map((label,i)=><div className="wb-attribute" key={label}><div><b>{label}</b><p>{meanings[i]}</p></div><NumberField label={label+' / 15'} value={p.stats[i]} min={1} max={15} step={.5} onChange={v=>update(d=>{d.stats[i]=v})}/><strong style={{color:statColor(p.stats[i])}}>{fmt(p.stats[i])}</strong></div>)}<p>Couleurs des capacités : rouge ≤ 5; jaune jusqu’à 10; vert au-dessus de 10. Palette modifiable dans le UI Gym.</p></section>
<section id="wb-development"><h3>Développement annuel automatique</h3><Source>Origine : potentiel de départ réévaluable + âge + saison vécue. Pas d’entraînement à gérer. Le calcul annuel reste à définir : aucun gain n’est inventé par cet éditeur.</Source><label>Marge de progression estimée<select value={p.potential} onChange={e=>update(d=>{d.potential=e.target.value})}>{['À évaluer','Très faible','Faible','Modeste','Moyen','Élevé','Très élevé'].map(v=><option key={v}>{v}</option>)}</select></label><p>Cette estimation n’ajoute aucun point aux attributs et ne promet pas un niveau final.</p><div className="pd-formula"><b>Âge + potentiel</b><span>ajustés par</span><b>Utilisation + performances + contexte de la saison</b></div><ul><li>Utilisation : où il a joué, sa régularité, sa position et ses partenaires.</li><li>Performances : bilan rapporté aux occasions; pas seulement les buts et passes.</li><li>Contexte : santé, énergie, confiance, moral et relations sur l’année entière.</li></ul><p><b>Rythme actuel : non calculé.</b> Les coefficients et la répartition des gains par attribut ne sont pas encore validés. L’historique constatera l’évolution, sans lui ajouter un bonus.</p></section>
<section id="wb-temperament"><h3>Personnalité et style</h3><Source>Origine : tendances du joueur, durables, sauf événement majeur. Modifiables ici pour concevoir le joueur; pas par le DG en partie. Aucun côté n’est supérieur et aucun choix ne modifie son talent.</Source>{axes.map((values,i)=><fieldset className="wb-axis" key={i}><legend>{['Personnalité · consignes','Personnalité · désaccords','Style de jeu · approche'][i]}</legend><div>{values.map((value,j)=><button type="button" key={value} aria-pressed={p.temperament[i]===j} onClick={()=>update(d=>{d.temperament[i]=j})}>{value}</button>)}</div></fieldset>)}<p>Les réactions aux événements et l’influence sur les relations restent à définir. « Créatif », « Loyal » et les anciens types ne sont plus des couches de bonus.</p></section>
<section id="wb-context"><h3>Contexte actuel</h3><Source>Origine : matchs, repos, événements et relations. Ces états sont évolutifs. Ici, tu poses une situation; aucun impact sur les attributs ni moyenne annuelle n’est simulé.</Source><div className="hp-fields">{(['energy','confidence','morale','relations'] as const).map((k,i)=><NumberField key={k} label={['Énergie / 100','Confiance / 100','Moral / 100','Relations / 100'][i]} value={p.context[k]} onChange={v=>update(d=>{d.context[k]=v})}/>)}<label>Santé<input value={p.context.injury} maxLength={200} onChange={e=>update(d=>{d.context.injury=e.target.value})}/></label><NumberField label="Absence (semaines)" value={p.context.injuryWeeks} max={104} onChange={v=>update(d=>{d.context.injuryWeeks=v})}/></div><p>Relations : indicateur de contexte pour les essais, pas encore une chimie calculée entre joueurs.</p></section>
<section id="wb-career"><h3>Carrière et observations</h3><Source>Origine : résultats de matchs et parcours. Ici, les saisons sont fictives et saisies à la main. Changer le tir ne réécrit pas les buts. Points = buts + passes.</Source>{p.seasons.map((season,i)=><fieldset key={i}><legend>{season.season} · {season.phase}</legend><div className="hp-fields">{(['gp','goals','assists'] as const).map((k,j)=><NumberField key={k} label={['Matchs','Buts','Passes'][j]+' · saison '+(i+1)} value={season[k]} max={1000} onChange={v=>update(d=>{d.seasons[i][k]=v})}/>)}</div><p>Points : {season.goals} + {season.assists} = <b>{season.goals+season.assists}</b></p></fieldset>)}
<h4>Historique des essais</h4><p>Enregistre un état pour suivre tes modifications. Ce sont des instantanés manuels, pas des saisons simulées.</p><label>Note de l’instantané<input value={note} maxLength={200} onChange={e=>setNote(e.target.value)}/></label><button className="quiet-btn" disabled={p.history.length>=100} onClick={()=>{update(d=>{d.history.push({date:new Date().toISOString(),stats:[...d.stats],note:note||'État du joueur'})});setNote('')}}>Enregistrer cet état</button>{p.history.length===0?<p>Aucun état enregistré.</p>:<ol className="wb-history">{p.history.map((h,i)=><li key={i}><b>{h.note}</b> · {h.date}<p>{labels.map((label,j)=>label+' '+fmt(h.stats[j])+(i?' ('+(h.stats[j]-p.history[i-1].stats[j]>=0?'+':'')+fmt(h.stats[j]-p.history[i-1].stats[j])+')':'')).join(' · ')}</p></li>)}</ol>}
<details><summary>Observations à 5 contre 5 et calculs avancés</summary><p>Données de test indépendantes des attributs. Les xG sont des estimations statistiques saisies; les ratios ci-dessous sont calculés.</p><div className="hp-fields">{Object.entries(rawLabels).map(([k,label])=><NumberField key={k} label={label} value={p.raw[k as keyof typeof p.raw]} max={k==='off'?100:100000} step={.1} onChange={v=>update(d=>{d.raw[k as keyof typeof d.raw]=v})}/>)}</div>{Object.entries(metrics).map(([k,v])=><p key={k}><b>{definitions[k][0]} : {fmt(v)}</b> · {definitions[k][1]}</p>)}</details></section>
<section id="wb-contract"><h3>Contrat et pari sur l’avenir</h3><Source>Origine : négociation et temps écoulé. Ici, valeurs de scénario. La demande salariale ne se recalcule pas encore selon les performances.</Source><div className="hp-fields"><NumberField label="Salaire annuel (M$)" value={p.contract.salary} max={30} step={.1} onChange={v=>update(d=>{d.contract.salary=v})}/><NumberField label="Saisons restantes" value={p.contract.years} max={8} onChange={v=>update(d=>{d.contract.years=v})}/><NumberField label="Demande annuelle (M$)" value={p.contract.demand} max={30} step={.1} onChange={v=>update(d=>{d.contract.demand=v})}/></div><p>Engagement restant : {fmt(p.contract.salary)} × {p.contract.years} = <b>{fmt(c.guaranteed)} M$</b>. {p.contract.years===0?'Contrat arrivé à échéance.':'Échéance dans '+p.contract.years+' saison(s).'}</p></section>
<section><h3>Notes du modèle</h3><textarea aria-label="Notes du joueur" value={p.notes} rows={5} maxLength={20000} onChange={e=>update(d=>{d.notes=e.target.value})}/></section>
</div><aside className="wb-preview" aria-label="Aperçu du même joueur"><span className="eyebrow">APERÇU · DONNÉES DE L’ÉDITEUR</span><h3>{p.identity.name}</h3><p>{p.identity.pos} · {p.identity.age} ans · {p.identity.height} · {p.identity.weight} lb</p><h4>Moyenne des attributs <strong style={{color:statColor(c.overall)}}>{fmt(c.overall)} / 15</strong></h4><p>Somme des sept attributs ÷ 7. Résumé arithmétique, pas une note de match.</p><Radar values={p.stats}/><div className="wb-preview-stats">{labels.map((label,i)=><div key={label}><span>{label}</span><b style={{color:statColor(p.stats[i])}}>{fmt(p.stats[i])}</b></div>)}</div><h4>Tendances</h4>{axes.map((row,i)=><p key={i}>{['Consignes','Désaccords','Approche'][i]} : <b>{row[p.temperament[i]]}</b></p>)}<p>Potentiel estimé : <b>{p.potential}</b></p><p>Énergie {p.context.energy} · Confiance {p.context.confidence} · Moral {p.context.morale} · Relations {p.context.relations} / 100</p><p>{p.context.injury} · Absence {p.context.injuryWeeks} sem.</p><p>{p.seasons[0].gp} MJ · {p.seasons[0].goals} B · {p.seasons[0].assists} A · <b>{c.points} PTS</b></p><p>{fmt(p.contract.salary)} M$/an · {p.contract.years} saison(s)</p></aside></div></section>}
