import {seed,labels} from './players';
export const catalogs={type:[...new Set(seed.map(p=>p.type))],playStyle:[...new Set(seed.map(p=>p.playStyle))],trait:[...new Set(seed.map(p=>p.trait))],potential:[...new Set(seed.map(p=>p.potential))]};
export type Category=keyof typeof catalogs;
export const descriptions:Record<string,string>={'Marqueur':'Cherche à terminer les occasions.','Polyvalent':'Peut remplir plusieurs fonctions.','Fabricant de jeux':'Cherche à préparer les occasions des autres.','Attaquant de puissance':'Utilise les duels et le jeu physique.','Direct':'Va rapidement au but.','Prudent':'Privilégie les options sûres.','Créatif':'Essaie des solutions inattendues.','Ambitieux':'Recherche progression et responsabilités.','Loyal':'Attachement envisagé au club.','Cupide':'Accorde une grande importance à la rémunération.'};
export const rawLabels:Record<string,string>={minutes:'Minutes à 5 contre 5',goals:'Buts à 5 contre 5',assists:'Passes à 5 contre 5',shots:'Tirs cadrés',ixg:'ixG individuel',cf:'CF · tentatives pour',ca:'CA · tentatives contre',ff:'FF · tentatives non bloquées pour',fa:'FA · tentatives non bloquées contre',xgf:'xGF · buts attendus pour',xga:'xGA · buts attendus contre',off:'xGF % sans le joueur'};
export const freshTemplate=()=>({version:1 as const,player:{...seed[0],name:'Modèle Hockey Player',age:25,num:0,stats:Array(7).fill(7),axes:[50,50],goals:0,assists:0,salary:1,years:1,league:1,team:1,height:'6 pi 0',weight:190,type:'Polyvalent',playStyle:'Direct',trait:'Loyal',potential:'Moyen'},energy:100,confidence:50,morale:50,injury:'En santé',injuryWeeks:0,notes:'',rules:Object.fromEntries(Object.entries(catalogs).map(([k,items])=>[k,Object.fromEntries(items.map(name=>[name,Array(7).fill(0)]))])) as Record<Category,Record<string,number[]>>,seasons:[{season:'2028–2029',phase:'Régulière',gp:0,goals:0,assists:0},{season:'2027–2028',phase:'Régulière',gp:0,goals:0,assists:0}],raw:{minutes:300,goals:5,assists:5,shots:50,ixg:5,cf:250,ca:250,ff:180,fa:180,xgf:15,xga:15,off:50}});
export type Template=ReturnType<typeof freshTemplate>;
export function calculate(t:Template){const bonuses=labels.map((_,i)=>Object.keys(catalogs).reduce((s,k)=>s+(t.rules[k as Category][t.player[k as Category]]?.[i]||0),0));const stats=t.player.stats.map((n,i)=>Math.max(1,Math.min(15,n+bonuses[i])));const mean=(a:number[])=>a.reduce((s,n)=>s+n,0)/a.length;return {stats,bonuses,overall:mean(stats),creation:mean([stats[0],stats[4]]),finishing:stats[1],recovery:(2*stats[5]+stats[2]+stats[6])/4,mobility:stats[3],guaranteed:t.player.salary*t.player.years};}
export function advanced(t:Template){const r=t.raw,divide=(a:number,b:number)=>b>0?a/b:null;return {p60:divide((r.goals+r.assists)*60,r.minutes),ixg60:divide(r.ixg*60,r.minutes),cfpct:divide(100*r.cf,r.cf+r.ca),ffpct:divide(100*r.ff,r.ff+r.fa),xgpct:divide(100*r.xgf,r.xgf+r.xga),xga60:divide(r.xga*60,r.minutes),finishing:r.goals-r.ixg,rel:r.xgf+r.xga>0?100*r.xgf/(r.xgf+r.xga)-r.off:null};}
// Reject malformed drafts before they can affect the live editor.
export function validTemplate(v:unknown):v is Template{try{const t=v as Template,b=freshTemplate();if(t.version!==1||!t.player||!t.rules||!t.raw||!Array.isArray(t.seasons)||t.seasons.length!==2)return false;const finite=(n:unknown,min:number,max:number)=>typeof n==='number'&&Number.isFinite(n)&&n>=min&&n<=max;
if(t.player.id!=='roy'||!['AG','C','AD'].includes(t.player.pos))return false;
if(!Array.isArray(t.player.stats)||t.player.stats.length!==7||!t.player.stats.every(n=>finite(n,1,15))||!Array.isArray(t.player.axes)||t.player.axes.length!==2||!t.player.axes.every(n=>finite(n,0,100)))return false;
for(const k of Object.keys(b.player)){const value=t.player[k as keyof typeof b.player],base=b.player[k as keyof typeof b.player];if(typeof base==='string'&&(typeof value!=='string'||value.length>200))return false;if(typeof base==='number'&&!finite(value,0,10000))return false;}
for(const k of Object.keys(catalogs) as Category[]){if(!catalogs[k].includes(t.player[k]))return false;for(const name of catalogs[k]){const row=t.rules[k]?.[name];if(!Array.isArray(row)||row.length!==7||!row.every(n=>finite(n,-5,5)))return false;}}
for(const k of Object.keys(b.raw))if(!finite(t.raw[k as keyof typeof b.raw],0,100000))return false;
for(const s of t.seasons)if(typeof s.season!=='string'||s.season.length>30||typeof s.phase!=='string'||s.phase.length>30||![s.gp,s.goals,s.assists].every(n=>finite(n,0,10000)))return false;
return [t.energy,t.confidence,t.morale].every(n=>finite(n,0,100))&&finite(t.injuryWeeks,0,104)&&typeof t.injury==='string'&&t.injury.length<=200&&typeof t.notes==='string'&&t.notes.length<=20000;}catch{return false;}}
