"use client";
import {useEffect,useState} from 'react';
import palette from './palette.json';
import {Search,RotateCcw,Download,Upload} from 'lucide-react';
import './palette.css';
export const PALETTE_STORAGE='hockey-palette-v1';
type Colors=Record<string,string>;
const valid=(v:unknown):v is string=>typeof v==='string'&&/^#[\da-f]{6}$/i.test(v);
export function PaletteEditor(){
 const [colors,setColors]=useState<Colors>({}),[query,setQuery]=useState(''),[all,setAll]=useState(false),[status,setStatus]=useState('');
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(PALETTE_STORAGE)||'{}');setColors(Object.fromEntries(palette.filter(p=>valid(saved[p.key])).map(p=>[p.key,saved[p.key]])))}catch{}},[]);
 function apply(next:Colors){setColors(next);for(const p of palette)document.documentElement.style.setProperty(`--palette-${p.key}`,next[p.key]||p.value);try{localStorage.setItem(PALETTE_STORAGE,JSON.stringify(next));setStatus('Palette sauvegardée sur cet appareil.')}catch{setStatus('Palette appliquée. Sauvegarde locale indisponible.')}}
 function change(key:string,value:string){if(valid(value))apply({...colors,[key]:value})}
 const shown=palette.filter(p=>(all||query||p.group!=='Nuances secondaires')&&`${p.label} ${p.group} ${p.uses.join(' ')} ${colors[p.key]||p.value}`.toLowerCase().includes(query.toLowerCase()));
 function exportPalette(){const blob=new Blob([JSON.stringify(Object.fromEntries(palette.map(p=>[p.key,colors[p.key]||p.value])),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='hockey-palette.json';a.click();URL.revokeObjectURL(url)}
 async function importPalette(file?:File){if(!file)return;try{const data=JSON.parse(await file.text());if(!data||typeof data!=='object'||Array.isArray(data))throw Error();const next:Colors={};for(const [k,v]of Object.entries(data)){if(!palette.some(p=>p.key===k)||!valid(v))throw Error();next[k]=v}apply(next)}catch{setStatus('Fichier invalide : utilise une palette exportée depuis le gym.')}}
 return <div className="palette-editor"><p>Une couleur modifiée se propage immédiatement partout où elle est utilisée. Les portraits illustrés conservent leurs couleurs.</p><div className="palette-tools"><label className="palette-search"><Search size={16}/><input aria-label="Chercher une couleur" placeholder="Chercher une couleur…" value={query} onChange={e=>setQuery(e.target.value)}/></label><button onClick={()=>setAll(!all)} aria-pressed={all}>{all?'Couleurs principales':`Toutes les nuances · ${palette.length}`}</button><button onClick={exportPalette}><Download size={16}/>Exporter</button><label className="palette-import"><Upload size={16}/>Importer<input type="file" accept="application/json" aria-label="Importer une palette" onChange={e=>{importPalette(e.target.files?.[0]);e.target.value=''}}/></label><button onClick={()=>apply({})}><RotateCcw size={16}/>Rétablir la palette</button></div><div className="palette-status" role="status">{status||'Changements locaux · Exportables pour les partager.'}</div><div className="palette-grid">{shown.map(p=><div className="palette-token" key={p.key}><label className="palette-swatch" style={{background:colors[p.key]||p.value}}><input type="color" aria-label={p.label} value={colors[p.key]||p.value} onChange={e=>change(p.key,e.target.value)}/></label><div><label htmlFor={`palette-${p.key}`}>{p.label}</label><small>{p.group}</small><input id={`palette-${p.key}`} aria-label={`${p.label} · code couleur`} key={colors[p.key]||p.value} defaultValue={colors[p.key]||p.value} maxLength={7} onBlur={e=>{if(valid(e.target.value))change(p.key,e.target.value);else{e.target.value=colors[p.key]||p.value;setStatus('Utilise un code à six caractères, précédé de #.')}}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur()}}/></div><button aria-label={`Rétablir ${p.label}`} disabled={!colors[p.key]} onClick={()=>{const next={...colors};delete next[p.key];apply(next)}}><RotateCcw size={14}/></button></div>)}</div>{!shown.length&&<p>Aucune couleur trouvée.</p>}</div>
}
