import {freshTemplate,validTemplate,advanced} from './hockey-player-model';
export const potentialLevels=['Très faible','Faible','Normal','Élevé','Très élevé'];
export const normalizePotential=(v:string)=>v==='Modeste'?'Faible':v==='Moyen'||v==='À évaluer'?'Normal':v;
export const potentialLabel=(v:string)=>`${potentialLevels.indexOf(normalizePotential(v))+1} · ${normalizePotential(v)}`;
export const axes=[['Rebelle','Neutre','Conformiste'],['Intransigeant','Neutre','Conciliant'],['Direct','Neutre','Prudent']];
export const freshPlayer=()=>{const old=freshTemplate();return {version:2 as const,identity:{name:old.player.name,age:25,num:0,pos:'AG',height:'6 pi 0',weight:190,league:0,team:0},stats:Array(7).fill(7) as number[],temperament:[1,1,1] as number[],potential:'Normal',context:{energy:100,confidence:50,morale:50,relations:50,injury:'En santé',injuryWeeks:0},contract:{salary:1,years:1,demand:1},seasons:old.seasons,raw:old.raw,notes:'',history:[] as {date:string;stats:number[];note:string}[]};};
export type WorkbenchPlayer=ReturnType<typeof freshPlayer>;
export function playerSummary(p:WorkbenchPlayer){return {overall:p.stats.reduce((s,n)=>s+n,0)/7,guaranteed:p.contract.salary*p.contract.years,points:p.seasons[0].goals+p.seasons[0].assists};}
export function observations(p:WorkbenchPlayer){return advanced({...freshTemplate(),raw:p.raw});}
export function migratePlayer(value:unknown):WorkbenchPlayer|null{if(!validTemplate(value))return null;const p=freshPlayer(),o=value;p.identity={name:o.player.name,age:o.player.age,num:o.player.num,pos:o.player.pos,height:o.player.height,weight:o.player.weight,league:o.player.league,team:o.player.team};p.stats=[...o.player.stats];p.temperament=[...o.player.axes.map(n=>n<34?0:n>66?2:1),o.player.playStyle==='Direct'?0:o.player.playStyle==='Prudent'?2:1];p.context={energy:o.energy,confidence:o.confidence,morale:o.morale,relations:50,injury:o.injury,injuryWeeks:o.injuryWeeks};p.contract={salary:o.player.salary,years:o.player.years,demand:o.player.salary};p.potential=normalizePotential(o.player.potential);p.seasons=structuredClone(o.seasons);p.raw={...o.raw};p.notes=o.notes;return p;}
export function validPlayer(v:unknown):v is WorkbenchPlayer{try{const p=v as WorkbenchPlayer;const number=(n:unknown,min:number,max:number)=>typeof n==='number'&&Number.isFinite(n)&&n>=min&&n<=max;const text=(s:unknown,max=200)=>typeof s==='string'&&s.length<=max;if(p.version!==2||!text(p.identity.name)||!text(p.identity.height)||!['AG','C','AD'].includes(p.identity.pos))return false;
if(!number(p.identity.age,0,100)||!number(p.identity.num,0,99)||!number(p.identity.weight,0,400)||!number(p.identity.league,0,100)||!number(p.identity.team,0,100))return false;
if(!Array.isArray(p.stats)||p.stats.length!==7||!p.stats.every(n=>number(n,1,15))||!Array.isArray(p.temperament)||p.temperament.length!==3||!p.temperament.every(n=>[0,1,2].includes(n)))return false;
if(!['À évaluer','Très faible','Faible','Modeste','Moyen','Normal','Élevé','Très élevé'].includes(p.potential)||!text(p.notes,20000))return false;
if(![p.context.energy,p.context.confidence,p.context.morale,p.context.relations].every(n=>number(n,0,100))||!text(p.context.injury)||!number(p.context.injuryWeeks,0,104)||!number(p.contract.salary,0,30)||!number(p.contract.demand,0,30)||!number(p.contract.years,0,8))return false;
if(!Array.isArray(p.seasons)||p.seasons.length!==2||!p.seasons.every(s=>text(s.season,30)&&text(s.phase,30)&&[s.gp,s.goals,s.assists].every(n=>number(n,0,1000))))return false;
if(!Object.keys(freshPlayer().raw).every(k=>number(p.raw[k as keyof typeof p.raw],0,k==='off'?100:100000)))return false;
return Array.isArray(p.history)&&p.history.length<=100&&p.history.every(h=>text(h.date,60)&&text(h.note,200)&&Array.isArray(h.stats)&&h.stats.length===7&&h.stats.every(n=>number(n,1,15)));}catch{return false;}}
