export function PlayerDesignGuide(){return <article className="player-design-guide" aria-label="Modèle du joueur retenu">
<header><span className="eyebrow">RÉFÉRENCE DU JEU · MODÈLE RETENU</span><h2>Un joueur. Une carrière. Tes décisions.</h2><p>Tu choisis sa place dans l’équipe et tu paries sur son avenir. Son développement se fait automatiquement à la fin de chaque saison, sans entraînement à gérer.</p></header>
<div className="pd-status"><b>Décisions de conception retenues</b><span>Cette page explique le modèle à construire. L’évolution annuelle, les réactions de personnalité et leurs effets sur les contrats ne sont pas encore simulés. L’éditeur ci-dessous utilise les attributs directement, sans les anciens bonus/malus de type ou de style.</span></div>
<section><h3>Les six parties du joueur</h3><div className="pd-grid">{[
['01','Le joueur aujourd’hui','BASE DU JOUEUR','Maniement, tir, puissance, patinage, IQ hockey, défense et cœur : sept attributs. Âge, taille, poids et expérience aux positions complètent son portrait.','Les capacités évoluent au fil de sa carrière. Aucun profil « marqueur » ou « créateur » nécessaire pour commencer.'],
['02','Son développement','ÉVOLUTION ANNUELLE','Le potentiel représente sa marge de progression. L’âge, son utilisation, ses performances et le contexte de sa saison influencent ce qu’il développe.','Progression automatique en fin de saison. Les coefficients et les règles par attribut restent à définir.'],
['03','Sa personnalité et son style','TENDANCES DURABLES','Deux axes de personnalité et un axe de style, présentés ci-dessous. Ce ne sont pas des notes de talent.','Ils ne changent jamais ou presque, sauf événement majeur. Aucun réglage de personnalité par le DG.'],
['04','Son contexte','ÉTAT ÉVOLUTIF','Énergie, confiance, moral, santé et relations avec les partenaires.','On suit leur évolution pendant la saison. Le contexte annuel compte, pas seulement l’état du dernier jour.'],
['05','Sa carrière','HISTORIQUE FACTUEL','Saisons, résultats, blessures, utilisation et changements d’attributs, avec leurs causes.','L’historique raconte ce qui est arrivé. Il ne donne pas un bonus de progression supplémentaire.'],
['06','Son contrat','DÉCISION ET ENGAGEMENT','Salaire, durée restante, demande salariale et échéance.','Signer tôt, attendre ou renouveler : tu prends des décisions à partir de ce que tu sais du joueur, sans connaître toute sa carrière.']
].map(([n,title,origin,body,evolution])=><section className="pd-card" key={n}><span className="eyebrow">{n} · {origin}</span><h4>{title}</h4><p>{body}</p><p className="pd-detail">{evolution}</p></section>)}</div></section>
<section><h3>Personnalité et style : trois axes, sans classement « bon / mauvais »</h3><p>Les trois repères aident à lire une tendance. Le neutre est au centre. Leurs effets précis en jeu restent à concevoir.</p>{[
['Personnalité · rapport aux consignes','Rebelle','Conformiste'],['Personnalité · rapport aux désaccords','Intransigeant','Conciliant'],['Style de jeu · façon d’aborder l’action','Direct','Prudent']
].map(([title,left,right])=><div className="pd-axis" key={title}><b>{title}</b><div><span>{left}</span><span>Neutre</span><span>{right}</span></div></div>)}<p>Ces repères sont explicatifs, pas des boutons pour changer le joueur. Le style « créatif » n’est pas conservé dans ce modèle; les capacités de création reposent sur les attributs.</p></section>
<section><h3>Comment se développe-t-il chaque année?</h3><div className="pd-formula"><b>Âge + marge de progression</b><span>ajustés par</span><b>Utilisation + performances + contexte de la saison</b><span>→ bilan annuel des changements d’attributs</span></div><p>Il s’agit du principe de calcul retenu, pas d’une addition numérique déjà implémentée.</p><div className="pd-grid">{[
['Potentiel','La marge qui reste à développer. Ce n’est pas une promesse que le joueur atteindra un niveau précis.'],
['Âge','Situe le joueur dans sa carrière. La courbe de progression et de déclin reste à définir.'],
['Utilisation','Où il a joué, sa régularité, sa position, son trio et les occasions reçues.'],
['Performances','Son bilan compte tenu de son utilisation. Les buts et passes ne suffisent pas à juger tous les joueurs.'],
['Contexte','Santé, fatigue, confiance, moral et relations vécus au fil de la saison.'],
['Rythme estimé','Une lecture de sa progression attendue, pas un réglage à gérer. On la compare ensuite au bilan réel.']
].map(([title,body])=><div className="pd-card" key={title}><h4>{title}</h4><p>{body}</p></div>)}</div></section>
<section className="pd-example"><h3>Ce que tu dois pouvoir comprendre</h3><p>Un jeune avec une bonne marge de progression, régulièrement utilisé et dans un contexte favorable peut progresser davantage qu’un jeune comparable souvent blessé ou peu utilisé. Une saison difficile ne signifie pas forcément que son potentiel a disparu.</p><p>À la fin de la saison : <b>attribut avant → attribut après → explication</b>. Les chiffres et l’incertitude devront être visibles une fois la simulation définie.</p></section>
<section><h3>Ce que tu gères</h3><p><b>Alignements, partenaires, occasions et contrats.</b> Tu peux t’attacher à un joueur, lui donner sa chance, miser sur sa progression ou décider de le laisser partir. Tu ne programmes pas ses séances d’entraînement.</p><p>Les joueurs ont un parcours depuis leur naissance. Le détail de sa génération avant leur arrivée dans ton équipe reste à définir.</p></section>
</article>}
