import {useState} from 'react';
import {labels} from './players';
import {axes,potentialLevels,type WorkbenchPlayer} from './player-workbench-model';
import {playerTags,awardTypes,matchesTags} from './player-tags';
import {statColor} from './stat-color';
export function PlayerTagsGym({player:p,update}:{player:WorkbenchPlayer;update:(fn:(p:WorkbenchPlayer)=>void)=>void}){const [family,setFamily]=useState('Tout'),[search,setSearch]=useState(''),[filters,setFilters]=useState<string[]>([]),[award,setAward]=useState('MVP'),[year,setYear]=useState(2029),[notice,setNotice]=useState('');const tags=playerTags(p),active=tags.filter(t=>t.active);const families=['Niveau actuel','Potentiel','Forces','Personnalité','Style','Parcours'];const normalized=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const visible=tags.filter(t=>(family==='Tout'||t.family===family)&&normalized(t.name+' '+t.rule).includes(normalized(search)));
return <section className="tag-gym"><header><span className="eyebrow">VALIDATION · PROFILS PAR TAGS</span><h2>Le joueur se décrit par ses tags.</h2><p>Un petit catalogue, plusieurs tags par joueur. Les tags décrivent ses capacités, ses tendances ou son parcours; ils ne donnent aucun bonus. Le joueur ci-dessous est le même que dans l’éditeur.</p></header>
<div className="wb-source"><b>Proposition à valider</b><p>Les seuils de niveau et de forces sont des règles d’essai affichées ci-dessous. Pour la personnalité, cette proposition utilise uniquement intransigeant / neutre / conciliant. L’ancien axe rebelle / conformiste reste conservé dans le brouillon, mais n’attribue aucun tag ici.</p></div>
<section className="tag-summary"><h3>{p.identity.name} · tags actuels</h3><div className="tag-chips">{active.map(t=><span key={t.id} title={t.rule}><small>{t.family}</small><b>{t.name}</b></span>)}</div><p>{active.length} tags actifs. Sur une petite carte, on pourra limiter l’affichage; ici tu vois tout pour valider.</p></section>
<div className="tag-columns"><section><h3>1. Modifier le joueur et observer</h3><p>Les tags calculés changent immédiatement. Les distinctions acquises restent.</p><div className="tag-stats">{labels.map((label,i)=><label key={label}>{label}<input aria-label={'Tags : '+label} type="number" min={1} max={15} step={.5} value={p.stats[i]} style={{color:statColor(p.stats[i])}} onChange={e=>{if(e.target.value!=='')update(d=>{d.stats[i]=Math.max(1,Math.min(15,Number(e.target.value)||1))})}}/></label>)}</div><label>Potentiel<select value={p.potential} onChange={e=>update(d=>{d.potential=e.target.value})}>{potentialLevels.map((v,i)=><option key={v} value={v}>{i+1} · {v}</option>)}</select></label>{[1,2].map(i=><fieldset className="wb-axis" key={i}><legend>{i===1?'Personnalité':'Style'}</legend><div>{axes[i].map((name,j)=><button key={name} aria-pressed={p.temperament[i]===j} onClick={()=>update(d=>{d.temperament[i]=j})}>{name}</button>)}</div></fieldset>)}<h4>Distinctions acquises</h4><p>Attribution manuelle de test. Aucun MVP n’est déduit automatiquement des buts.</p><div className="hp-fields"><label>Distinction<select value={award} onChange={e=>setAward(e.target.value)}>{awardTypes.map(v=><option key={v}>{v}</option>)}</select></label><label>Saison<input aria-label="Saison de la distinction" type="number" min={1900} max={2200} step={1} value={year} onChange={e=>setYear(Number(e.target.value))}/></label></div><button className="quiet-btn" disabled={!Number.isInteger(year)||year<1900||year>2200||(p.awards||[]).length>=50} onClick={()=>{if((p.awards||[]).some(a=>a.type===award&&a.year===year)){setNotice('Cette distinction est déjà enregistrée.');return}update(d=>{d.awards=[...(d.awards||[]),{type:award,year}]});setNotice('Distinction ajoutée au parcours.')}}>Ajouter la distinction</button><p role="status">{notice}</p>{(p.awards||[]).map((a,i)=><p key={i}>{a.type} · {a.year} <button className="quiet-btn" aria-label={'Retirer '+a.type+' '+a.year} onClick={()=>update(d=>{d.awards=(d.awards||[]).filter((_,j)=>j!==i)})}>Retirer du test</button></p>)}</section>
<section><h3>2. Catalogue et règles exactes</h3><p>22 tags de caractéristiques possibles, regroupés en cinq familles, plus 3 types de distinctions datées. Tous les tags ne s’excluent pas : un joueur peut être généraliste et fort en tir.</p><div className="hp-fields"><label>Famille<select value={family} onChange={e=>setFamily(e.target.value)}>{['Tout',...families].map(v=><option key={v}>{v}</option>)}</select></label><label>Rechercher dans le catalogue<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tireur, potentiel, règle…"/></label></div><div className="tag-catalog">{visible.map(t=><article key={t.id} className={t.active?'is-active':''}><div><small>{t.family} · {t.active?'ACTIF':'INACTIF'}</small><h4>{t.name}</h4></div><p>{t.rule}</p><small>{t.origin}</small></article>)}</div>{visible.length===0&&<p>Aucun tag correspondant.</p>}{(family==='Tout'||family==='Parcours')&&<p>Catalogue du parcours : {awardTypes.join(' · ')}. Chaque distinction devient un tag avec sa saison, par exemple « MVP · 2019 ».</p>}</section></div>
<section><h3>3. Essayer la recherche par combinaison</h3><p>Sélectionne des tags : le joueur doit tous les posséder. Ce test porte sur ton modèle actuel; il ne recherche pas encore dans toute la ligue.</p><div className="tag-filter-list">{tags.map(t=><button key={t.id} aria-pressed={filters.includes(t.id)} onClick={()=>setFilters(old=>old.includes(t.id)?old.filter(id=>id!==t.id):[...old,t.id])}>{t.name}</button>)}</div><button className="quiet-btn" onClick={()=>setFilters([])}>Effacer les filtres</button><p className="tag-match" role="status">{filters.length===0?'Aucun filtre : le joueur est inclus.':matchesTags(p,filters)?'✓ Le joueur correspond à tous les tags choisis.':'Le joueur ne correspond pas à tous les tags choisis.'}</p>{filters.length>0&&<p>Manquants : {filters.filter(id=>!active.some(t=>t.id===id)).map(id=>tags.find(t=>t.id===id)?.name||'Distinction retirée').join(', ')||'aucun'}.</p>}</section>
<section><h3>4. Ce qu’on valide</h3><ul><li>Les seuils de niveau : moins de 6, de 6 à moins de 10, au moins 10.</li><li>Les forces : au moins 10/15, à deux points maximum du meilleur attribut.</li><li>Le généraliste : deux points maximum entre ses extrêmes.</li><li>Un seul axe de personnalité suffit-il avec le style?</li><li>Les trois distinctions proposées sont-elles utiles?</li></ul><p>Les attributs, tendances, distinctions et notes sont sauvegardés et exportés avec le joueur.</p><label>Notes de validation<textarea aria-label="Notes de validation des tags" rows={5} maxLength={20000} value={p.notes} onChange={e=>update(d=>{d.notes=e.target.value})}/></label></section>
</section>}
