import {useState} from 'react';
import {labels} from './players';
import {Radar} from './player-radar';
import {statColor} from './stat-color';
import {axes,freshPlayer,playerSummary,potentialLabel,type WorkbenchPlayer} from './player-workbench-model';
const fmt=(n:number)=>n.toLocaleString('fr-CA',{maximumFractionDigits:2});
export function GymNumberField({label,value,onChange,min=0,max=100,step=1}:{label:string;value:number;onChange:(v:number)=>void;min?:number;max?:number;step?:number}){return <label>{label}<input type="number" aria-label={label} value={value} min={min} max={max} step={step} onChange={e=>{if(e.target.value!==''&&Number.isFinite(Number(e.target.value)))onChange(Math.max(min,Math.min(max,Number(e.target.value))))}}/></label>}
export function GymOrigin({children}:{children:React.ReactNode}){return <p className="ui-origin">{children}</p>}
export function GymChoice({label,options,value,onChange}:{label:string;options:string[];value:number;onChange:(v:number)=>void}){return <fieldset className="ui-choice"><legend>{label}</legend><div>{options.map((name,i)=><button type="button" key={name} aria-pressed={value===i} onClick={()=>onChange(i)}>{name}</button>)}</div></fieldset>}
export function GymPlayerSummary({player:p}:{player:WorkbenchPlayer}){const c=playerSummary(p);return <aside className="ui-player-summary" aria-label="Aperçu du même joueur"><span className="eyebrow">APERÇU · DONNÉES DE L’ÉDITEUR</span><h3>{p.identity.name}</h3><p>{p.identity.pos} · {p.identity.age} ans · {p.identity.height} · {p.identity.weight} lb</p><h4>Moyenne des attributs <strong style={{color:statColor(c.overall)}}>{fmt(c.overall)} / 15</strong></h4><p>Somme des sept attributs ÷ 7. Résumé arithmétique, pas une note de match.</p><Radar values={p.stats}/><div className="ui-player-summary-stats">{labels.map((label,i)=><div className="ui-stat-row" key={label}><span>{label}</span><b style={{color:statColor(p.stats[i])}}>{fmt(p.stats[i])}</b></div>)}</div><h4>Tendances</h4>{axes.map((row,i)=><p key={i}>{['Consignes','Désaccords','Approche'][i]} : <b>{row[p.temperament[i]]}</b></p>)}<p>Potentiel estimé : <b>{potentialLabel(p.potential)}</b></p><p>Énergie {p.context.energy} · Confiance {p.context.confidence} · Moral {p.context.morale} · Relations {p.context.relations} / 100</p><p>{p.context.injury} · Absence {p.context.injuryWeeks} sem.</p><p>{p.seasons[0].gp} MJ · {p.seasons[0].goals} B · {p.seasons[0].assists} A · <b>{c.points} PTS</b></p><p>{fmt(p.contract.salary)} M$/an · {p.contract.years} saison(s)</p></aside>}
export function SharedPlayerDemo(){const [p,setP]=useState(freshPlayer);return <div className="ui-gym-surface"><GymOrigin>Composants de référence utilisés par Hockey Player : même fiche, radar, champs et choix. Toute correction ici s’applique à l’éditeur.</GymOrigin><GymNumberField label="Tir de démonstration" value={p.stats[1]} min={1} max={15} step={.5} onChange={v=>setP({...p,stats:p.stats.map((n,i)=>i===1?v:n)})}/><GymChoice label="Style de démonstration" options={axes[2]} value={p.temperament[2]} onChange={v=>setP({...p,temperament:[p.temperament[0],p.temperament[1],v]})}/><GymPlayerSummary player={p}/></div>}
